import { Gender, Person } from "./types";

const nodeDataArray: Person[] = [
  {
    key: 0,
    name: "عبد الحفيظ بن محمد الخنقي",
    gender: Gender.M,
    birthYear: "-",
    deathYear: "-",
  },
  {
    key: 1,
    parent: 0,
    name: "الحفناوي",
    gender: Gender.M,
    birthYear: "-",
    deathYear: "-",
  },
  {
    key: 2,
    parent: 0,
    name: "الأزهاري",
    gender: Gender.M,
    birthYear: "-",
    deathYear: "-",
  },
  {
    key: 3,
    parent: 0,
    name: "محمود",
    gender: Gender.M,
    birthYear: "-",
    deathYear: "-",
  },
  {
    key: 4,
    parent: 0,
    name: "صفية",
    gender: Gender.F,
    birthYear: "-",
    deathYear: "-",
  },
  {
    key: 5,
    parent: 1,
    name: "إبراهيم",
    gender: Gender.M,
    birthYear: "-",
    deathYear: "-",
  },
  {
    key: 6,
    parent: 1,
    name: "الطيب",
    gender: Gender.M,
    birthYear: "-",
    deathYear: "-",
  },
  {
    key: 7,
    parent: 1,
    name: "العربي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 8,
    parent: 1,
    name: "المكي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 9,
    parent: 1,
    name: "البشير",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 10,
    parent: 1,
    name: "عبد القادر",
    gender: Gender.M,
    birthYear: "-",
  },
  { key: 11, parent: 1, name: "علي", gender: Gender.M, birthYear: "-" },
  {
    key: 12,
    parent: 1,
    name: "بنعزوز",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 13,
    parent: 1,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  { key: 14, parent: 5, name: "الأزهاري", gender: Gender.M, birthYear: "-" },
  {
    key: 15,
    parent: 5,
    name: "عبد الحفيظ",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 16,
    parent: 5,
    name: "علي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 17,
    parent: 5,
    name: "علجية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 18,
    parent: 5,
    name: "منى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 19,
    parent: 14,
    name: "الجنيدي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 20,
    parent: 14,
    name: "الأمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 21,
    parent: 14,
    name: "التارزي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 22,
    parent: 14,
    name: "عبد اللطيف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 23,
    parent: 14,
    name: "إبراهيم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 24,
    parent: 14,
    name: "يمينة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 26,
    parent: 14,
    name: "فطيمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 27,
    parent: 14,
    name: "نجمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 28,
    parent: 14,
    name: "سعدية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 29,
    parent: 14,
    name: "حفصة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 30,
    parent: 6,
    name: "الأمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 31,
    parent: 6,
    name: "المأمون",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 32,
    parent: 6,
    name: "الوردي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 33,
    parent: 6,
    name: "عبد الحفيظ",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 34,
    parent: 6,
    name: "مباركة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 35,
    parent: 6,
    name: "بشرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 36,
    parent: 6,
    name: "صليحة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 37,
    parent: 6,
    name: "الزهراء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 38,
    parent: 6,
    name: "دلولة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 39,
    parent: 6,
    name: "فطيمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 40,
    parent: 30,
    name: "إبراهيم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 41,
    parent: 40,
    name: "الصديقية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 42,
    parent: 40,
    name: "ربيعة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 43,
    parent: 40,
    name: "رشيدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 44,
    parent: 40,
    name: "نجمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 45,
    parent: 31,
    name: "أحمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 46,
    parent: 31,
    name: "الأزهر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 47,
    parent: 31,
    name: "الطيب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 48,
    parent: 31,
    name: "عزوز",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 49,
    parent: 31,
    name: "محمود",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 50,
    parent: 31,
    name: "رحيمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 51,
    parent: 31,
    name: "ليلى",
    gender: Gender.F,
    birthYear: "-",
  },
  { key: 52, parent: 31, name: "صفية", gender: Gender.F, birthYear: "-" },
  {
    key: 53,
    parent: 31,
    name: "فائزة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 54,
    parent: 31,
    name: "دلولة",
    gender: Gender.F,
    birthYear: "-",
  },
  { key: 55, parent: 31, name: "يمينة", gender: Gender.F, birthYear: "-" },
  {
    key: 56,
    parent: 33,
    name: "الأزهاري",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 58,
    parent: 33,
    name: "نجوى",
    gender: Gender.F,
    birthYear: "-",
  },
  { key: 59, parent: 33, name: "منال", gender: Gender.F, birthYear: "-" },
  {
    key: 60,
    parent: 33,
    name: "منية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 61,
    parent: 33,
    name: "وسيلة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 62,
    parent: 32,
    name: "محمود",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 63,
    parent: 32,
    name: "الطيب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 64,
    parent: 32,
    name: "الحفناوي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 65,
    parent: 32,
    name: "فضيلة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 66,
    parent: 32,
    name: "فتحية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 67,
    parent: 32,
    name: "يمينة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 68,
    parent: 10,
    name: "عبد الحفيظ",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 69,
    parent: 10,
    name: "عبد اللطيف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 70,
    parent: 10,
    name: "عبد الستار",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 71,
    parent: 10,
    name: "عبد الشافي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 72,
    parent: 10,
    name: "علجية",
    gender: Gender.F,
    birthYear: "-",
  },
  { key: 73, parent: 10, name: "فاطمة", gender: Gender.F, birthYear: "-" },
  { key: 74, parent: 10, name: "خديجة", gender: Gender.F, birthYear: "-" },
  {
    key: 75,
    parent: 69,
    name: "عبد القادر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 76,
    parent: 69,
    name: "غانم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 77,
    parent: 69,
    name: "فريد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 78,
    parent: 69,
    name: "حسن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 79,
    parent: 69,
    name: "فائزة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 80,
    parent: 69,
    name: "حليمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 81,
    parent: 69,
    name: "سعيدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 82,
    parent: 69,
    name: "ثريا",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 83,
    parent: 69,
    name: "هنية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 84,
    parent: 70,
    name: "عبد السميع",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 85,
    parent: 70,
    name: "صالح",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 86,
    parent: 70,
    name: "عبد القادر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 87,
    parent: 70,
    name: "سالمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 88,
    parent: 84,
    name: "حمزة",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 89,
    parent: 84,
    name: "طه",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 90,
    parent: 84,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 91,
    parent: 89,
    name: "لجينة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 92,
    parent: 90,
    name: "أحمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 93,
    parent: 90,
    name: "يوسف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 94,
    parent: 90,
    name: "آدم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 95,
    parent: 90,
    name: "إيناس",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 96,
    parent: 85,
    name: "ضياء",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 97,
    parent: 85,
    name: "أسامة",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 98,
    parent: 85,
    name: "رحاب",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 99,
    parent: 85,
    name: "أسماء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 100,
    parent: 85,
    name: "رحمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 101,
    parent: 85,
    name: "ضحى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 102,
    parent: 71,
    name: "الهادي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 103,
    parent: 71,
    name: "رضا",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 104,
    parent: 71,
    name: "الأزهر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 105,
    parent: 71,
    name: "وسيلة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 106,
    parent: 71,
    name: "سعيدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 107,
    parent: 102,
    name: "إيمان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 108,
    parent: 102,
    name: "ألفة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 109,
    parent: 102,
    name: "عاطف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 110,
    parent: 102,
    name: "منى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 111,
    parent: 102,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 112,
    parent: 103,
    name: "أحمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 113,
    parent: 103,
    name: "شذى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 114,
    parent: 103,
    name: "أمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 115,
    parent: 103,
    name: "شهد",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 116,
    parent: 68,
    name: "عبد القدوس",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 117,
    parent: 68,
    name: "لطفي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 118,
    parent: 68,
    name: "فوزي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 119,
    parent: 68,
    name: "رابحة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 120,
    parent: 68,
    name: "زكية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 121,
    parent: 68,
    name: "فريدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 122,
    parent: 68,
    name: "فوزية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 123,
    parent: 11,
    name: "منصور",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 124,
    parent: 11,
    name: "أحمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 125,
    parent: 11,
    name: "الأمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 126,
    parent: 11,
    name: "زبيدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 127,
    parent: 11,
    name: "فاطمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 128,
    parent: 11,
    name: "الزهرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 129,
    parent: 123,
    name: "محمد الطاهر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 130,
    parent: 123,
    name: "عبد القادر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 131,
    parent: 123,
    name: "محمد الصالح",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 132,
    parent: 123,
    name: "محمد الباقر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 133,
    parent: 123,
    name: "الحبيب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 134,
    parent: 123,
    name: "عبد العزيز",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 135,
    parent: 123,
    name: "العطرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 136,
    parent: 124,
    name: "عبد الرؤوف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 137,
    parent: 125,
    name: "علي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 138,
    parent: 126,
    name: "لأخضر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 139,
    parent: 127,
    name: "نجيبة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 140,
    parent: 128,
    name: "الصافية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 141,
    parent: 129,
    name: "حفصة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 142,
    parent: 130,
    name: "كلثوم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 143,
    parent: 131,
    name: "زينب",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 144,
    parent: 138,
    name: "خالد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 145,
    parent: 138,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 146,
    parent: 138,
    name: "هاشم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 147,
    parent: 138,
    name: "عماد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 148,
    parent: 138,
    name: "خديجة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 149,
    parent: 136,
    name: "شوقي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 150,
    parent: 136,
    name: "سمية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 151,
    parent: 136,
    name: "خولة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 152,
    parent: 136,
    name: "وفاء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 153,
    parent: 137,
    name: "ماهر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 154,
    parent: 137,
    name: "حسام",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 155,
    parent: 137,
    name: "شيماء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 156,
    parent: 125,
    name: "منير",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 157,
    parent: 125,
    name: "عدنان",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 158,
    parent: 125,
    name: "فتحي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 159,
    parent: 125,
    name: "عادل",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 160,
    parent: 125,
    name: "شوقي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 161,
    parent: 125,
    name: "ثريا",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 162,
    parent: 156,
    name: "أمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 163,
    parent: 156,
    name: "سارة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 164,
    parent: 156,
    name: "مروى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 165,
    parent: 156,
    name: "اميمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 166,
    parent: 157,
    name: "يحيى",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 167,
    parent: 157,
    name: "يسرى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 168,
    parent: 157,
    name: "رباب",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 169,
    parent: 157,
    name: "مروى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 170,
    parent: 158,
    name: "ياسين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 171,
    parent: 158,
    name: "محمد الأمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 172,
    parent: 158,
    name: "إيناس",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 173,
    parent: 159,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 174,
    parent: 159,
    name: "جيهان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 175,
    parent: 160,
    name: "منال",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 176,
    parent: 160,
    name: "ملاك",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 177,
    parent: 160,
    name: "أميرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 178,
    parent: 7,
    name: "محمود",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 179,
    parent: 7,
    name: "التارزي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 180,
    parent: 7,
    name: "عبد الرحمان",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 181,
    parent: 7,
    name: "الأزهاري",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 182,
    parent: 7,
    name: "الطيب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 183,
    parent: 7,
    name: "عامر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 184,
    parent: 7,
    name: "إبراهيم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 185,
    parent: 7,
    name: "صفية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 186,
    parent: 7,
    name: "دلولة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 187,
    parent: 7,
    name: "خديجة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 188,
    parent: 7,
    name: "مريم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 189,
    parent: 7,
    name: "عائشة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 190,
    parent: 178,
    name: "عبد الحفيظ",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 191,
    parent: 178,
    name: "الأزهر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 192,
    parent: 178,
    name: "بشرى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 193,
    parent: 178,
    name: "زبيدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 194,
    parent: 178,
    name: "فطيمه",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 195,
    parent: 178,
    name: "أم الخير",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 196,
    parent: 190,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 197,
    parent: 190,
    name: "التارزي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 198,
    parent: 190,
    name: "حسن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 199,
    parent: 190,
    name: "المنذر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 200,
    parent: 190,
    name: "هدى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 201,
    parent: 190,
    name: "فضيلة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 202,
    parent: 190,
    name: "ليلى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 203,
    parent: 190,
    name: "حليمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 204,
    parent: 190,
    name: "سامية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 205,
    parent: 191,
    name: "صابر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 206,
    parent: 191,
    name: "محمود",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 207,
    parent: 191,
    name: "وضاح",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 208,
    parent: 191,
    name: "المنذر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 209,
    parent: 191,
    name: "نجمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 210,
    parent: 191,
    name: "رندة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 211,
    parent: 191,
    name: "يسرى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 212,
    parent: 191,
    name: "مريم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 213,
    parent: 196,
    name: "محمد عزيز",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 214,
    parent: 196,
    name: "خلود",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 215,
    parent: 196,
    name: "خولة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 216,
    parent: 197,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 217,
    parent: 197,
    name: "سارة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 218,
    parent: 197,
    name: "مريم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 219,
    parent: 198,
    name: "طارق",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 220,
    parent: 198,
    name: "أحمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 221,
    parent: 198,
    name: "كنزة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 222,
    parent: 199,
    name: "مؤيد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 223,
    parent: 199,
    name: "محمد ياسين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 224,
    parent: 199,
    name: "ياسمين",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 225,
    parent: 205,
    name: "محمد امين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 226,
    parent: 179,
    name: "محمد الصالح",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 227,
    parent: 179,
    name: "علي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 228,
    parent: 179,
    name: "فوزي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 229,
    parent: 179,
    name: "فريد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 230,
    parent: 179,
    name: "سعاد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 231,
    parent: 179,
    name: "عواطف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 232,
    parent: 228,
    name: "دعاء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 233,
    parent: 228,
    name: "يقين",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 234,
    parent: 228,
    name: "ماجدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 235,
    parent: 229,
    name: "فراس",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 236,
    parent: 229,
    name: "سمر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 237,
    parent: 229,
    name: "تقوى",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 238,
    parent: 229,
    name: "آية",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 239,
    parent: 227,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 240,
    parent: 227,
    name: "سيف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 241,
    parent: 227,
    name: "إلهام",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 242,
    parent: 227,
    name: "سلوى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 243,
    parent: 227,
    name: "سناء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 244,
    parent: 239,
    name: "علي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 245,
    parent: 239,
    name: "آدم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 246,
    parent: 239,
    name: "ميسان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 247,
    parent: 180,
    name: "إبراهيم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 248,
    parent: 180,
    name: "التارزي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 249,
    parent: 180,
    name: "عامر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 250,
    parent: 180,
    name: "فردوس",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 251,
    parent: 180,
    name: "مباركة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 252,
    parent: 247,
    name: "وجيه",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 253,
    parent: 247,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 254,
    parent: 247,
    name: "صدام",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 255,
    parent: 247,
    name: "وهبي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 256,
    parent: 247,
    name: "منى",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 257,
    parent: 247,
    name: "فاتن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 258,
    parent: 249,
    name: "أسامة",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 259,
    parent: 249,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 260,
    parent: 249,
    name: "أمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 261,
    parent: 249,
    name: "أحمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 262,
    parent: 249,
    name: "رحاب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 263,
    parent: 181,
    name: "عبد الخالق",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 264,
    parent: 181,
    name: "عبد الحي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 265,
    parent: 181,
    name: "صليحة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 266,
    parent: 263,
    name: "إيهاب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 267,
    parent: 263,
    name: "مهاب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 268,
    parent: 263,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 269,
    parent: 263,
    name: "إحسان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 270,
    parent: 263,
    name: "حنان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 271,
    parent: 263,
    name: "مها",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 272,
    parent: 182,
    name: "عبد الله",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 273,
    parent: 182,
    name: "الجموعي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 274,
    parent: 182,
    name: "عبد الحفيظ",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 275,
    parent: 182,
    name: "فتحية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 276,
    parent: 272,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 277,
    parent: 272,
    name: "ألفة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 278,
    parent: 272,
    name: "وفاء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 279,
    parent: 272,
    name: "سماح",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 280,
    parent: 273,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 281,
    parent: 273,
    name: "حسن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 282,
    parent: 273,
    name: "نجاح",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 283,
    parent: 273,
    name: "عبير",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 284,
    parent: 273,
    name: "إيمان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 285,
    parent: 274,
    name: "محمد المكي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 286,
    parent: 12,
    name: "عبد الحفيظ",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 287,
    parent: 12,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 288,
    parent: 12,
    name: "البناني",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 289,
    parent: 12,
    name: "نجمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 290,
    parent: 12,
    name: "السعدية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 291,
    parent: 12,
    name: "رضية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 292,
    parent: 12,
    name: "زبيدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 293,
    parent: 12,
    name: "حليمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 294,
    parent: 288,
    name: "نجية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 295,
    parent: 288,
    name: "نفسية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 296,
    parent: 286,
    name: "محمد الحسن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 297,
    parent: 286,
    name: "كلثوم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 298,
    parent: 286,
    name: "العطرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 299,
    parent: 286,
    name: "مريم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 300,
    parent: 286,
    name: "فطيمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 301,
    parent: 296,
    name: "محمد جمال",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 302,
    parent: 296,
    name: "محمد البناني",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 303,
    parent: 296,
    name: "رشيدة",
    gender: Gender.F,
    birthYear: "-",
    description: "متوفية، رحمها الله",
  },
  {
    key: 304,
    parent: 301,
    name: "عمر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 305,
    parent: 301,
    name: "حسن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 306,
    parent: 301,
    name: "أنيس",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 307,
    parent: 302,
    name: "مهدي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 308,
    parent: 302,
    name: "وعد",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 309,
    parent: 302,
    name: "وفاء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 310,
    parent: 302,
    name: "نادية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 311,
    parent: 287,
    name: "المولدي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 312,
    parent: 287,
    name: "احمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 313,
    parent: 287,
    name: "البكري",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 314,
    parent: 287,
    name: "عبد الحفيظ",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 315,
    parent: 287,
    name: "الحسين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 316,
    parent: 287,
    name: "بنعزوز",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 317,
    parent: 287,
    name: "المنجي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 318,
    parent: 287,
    name: "الحبيب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 319,
    parent: 287,
    name: "العربي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 320,
    parent: 287,
    name: "زليخة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 321,
    parent: 287,
    name: "خديجة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 322,
    parent: 287,
    name: "جميلة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 323,
    parent: 287,
    name: "فريدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 324,
    parent: 287,
    name: "عيشوش",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 325,
    parent: 287,
    name: "مريم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 326,
    parent: 287,
    name: "نعيمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 327,
    parent: 311,
    name: "عاطف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 328,
    parent: 311,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 329,
    parent: 311,
    name: "هدى 1",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 330,
    parent: 311,
    name: "هدى 2",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 331,
    parent: 311,
    name: "أزر",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 332,
    parent: 311,
    name: "حبيبة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 333,
    parent: 312,
    name: "عصام",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 334,
    parent: 312,
    name: "عماد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 335,
    parent: 312,
    name: "حمزة",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 336,
    parent: 312,
    name: "منال",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 337,
    parent: 334,
    name: "أمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 338,
    parent: 313,
    name: "أيمن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 339,
    parent: 313,
    name: "أحمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 340,
    parent: 313,
    name: "حاتم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 341,
    parent: 313,
    name: "نادية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 342,
    parent: 313,
    name: "حنان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 343,
    parent: 313,
    name: "ندى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 344,
    parent: 313,
    name: "رحاب",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 345,
    parent: 314,
    name: "عفاف",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 346,
    parent: 314,
    name: "تهاني",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 347,
    parent: 314,
    name: "بسام",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 348,
    parent: 314,
    name: "أنور",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 349,
    parent: 314,
    name: "أنس",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 350,
    parent: 316,
    name: "هيثم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 351,
    parent: 316,
    name: "مراد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 352,
    parent: 316,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 353,
    parent: 316,
    name: "اخلاص",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 354,
    parent: 316,
    name: "خولة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 355,
    parent: 317,
    name: "وضاح",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 356,
    parent: 317,
    name: "خديجة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 357,
    parent: 317,
    name: "آمنة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 358,
    parent: 319,
    name: "عبد الحق",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 359,
    parent: 319,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 360,
    parent: 319,
    name: "نبيل",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 361,
    parent: 319,
    name: "أميرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 362,
    parent: 315,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 363,
    parent: 315,
    name: "لبنى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 364,
    parent: 315,
    name: "هندة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 365,
    parent: 315,
    name: "سندس",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 366,
    parent: 315,
    name: "ريم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 367,
    parent: 8,
    name: "العربي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 368,
    parent: 8,
    name: "المولدي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 369,
    parent: 8,
    name: "محمد الأخضر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 370,
    parent: 8,
    name: "محمد الأمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 371,
    parent: 8,
    name: "الصادق",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 372,
    parent: 8,
    name: "نجمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 373,
    parent: 8,
    name: "اليامنة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 374,
    parent: 8,
    name: "الزهراء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 375,
    parent: 8,
    name: "العطرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 376,
    parent: 8,
    name: "فاطمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 377,
    parent: 8,
    name: "تركية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 378,
    parent: 8,
    name: "اليامنة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 379,
    parent: 8,
    name: "رقية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 380,
    parent: 8,
    name: "مريم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 381,
    parent: 367,
    name: "الحفناوي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 382,
    parent: 367,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 383,
    parent: 367,
    name: "وليد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 384,
    parent: 367,
    name: "رابحة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 385,
    parent: 367,
    name: "صفاء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 386,
    parent: 367,
    name: "هاجر",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 387,
    parent: 367,
    name: "سناء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 388,
    parent: 368,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 389,
    parent: 368,
    name: "مراد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 390,
    parent: 368,
    name: "ملاك",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 391,
    parent: 13,
    name: "الطاهر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 392,
    parent: 13,
    name: "خدوج",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 393,
    parent: 391,
    name: "معروف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 394,
    parent: 391,
    name: "عبد المجيد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 395,
    parent: 391,
    name: "الوردي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 396,
    parent: 391,
    name: "الحفناوي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 397,
    parent: 391,
    name: "نور الدين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 398,
    parent: 391,
    name: "السعدية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 399,
    parent: 391,
    name: "الزهراء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 400,
    parent: 393,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 401,
    parent: 393,
    name: "معاذ",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 402,
    parent: 393,
    name: "مالك",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 403,
    parent: 393,
    name: "فؤاد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 404,
    parent: 400,
    name: "عبد الرؤوف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 405,
    parent: 400,
    name: "نور الدين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 406,
    parent: 400,
    name: "تقي الدين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 407,
    parent: 400,
    name: "عبد المنعم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 408,
    parent: 400,
    name: "نور الهدى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 409,
    parent: 400,
    name: "نعيمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 410,
    parent: 400,
    name: "نادية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 411,
    parent: 400,
    name: "سارة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 412,
    parent: 400,
    name: "نبيهة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 413,
    parent: 400,
    name: "منيرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 414,
    parent: 400,
    name: "أحلام",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 415,
    parent: 400,
    name: "منال",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 416,
    parent: 400,
    name: "أزهار",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 417,
    parent: 400,
    name: "أنيسة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 418,
    parent: 402,
    name: "الزبير",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 419,
    parent: 402,
    name: "الزائر",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 420,
    parent: 402,
    name: "ياسمينة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 421,
    parent: 402,
    name: "هناء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 422,
    parent: 402,
    name: "مباركة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 57,
    parent: 402,
    name: "حياة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 423,
    parent: 402,
    name: "خولة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 424,
    parent: 402,
    name: "لبنى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 425,
    parent: 402,
    name: "سامية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 426,
    parent: 401,
    name: "عبد الحكيم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 427,
    parent: 401,
    name: "فوزي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 428,
    parent: 401,
    name: "عبد الدائم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 429,
    parent: 401,
    name: "عبد المطلب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 430,
    parent: 401,
    name: "عصام",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 431,
    parent: 426,
    name: "وليد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 432,
    parent: 426,
    name: "زليخة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 433,
    parent: 426,
    name: "وفاء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 434,
    parent: 426,
    name: "نسرين",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 435,
    parent: 403,
    name: "فيصل",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 436,
    parent: 403,
    name: "زهير",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 437,
    parent: 403,
    name: "نبيل",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 438,
    parent: 403,
    name: "محمد الصالح",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 439,
    parent: 403,
    name: "زياد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 440,
    parent: 403,
    name: "هدى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 441,
    parent: 403,
    name: "آمال",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 442,
    parent: 394,
    name: "رحيمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 443,
    parent: 397,
    name: "إلياس",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 444,
    parent: 397,
    name: "مروان",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 445,
    parent: 397,
    name: "محمد الصالح",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 446,
    parent: 397,
    name: "سعدان",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 447,
    parent: 397,
    name: "نسرين",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 448,
    parent: 397,
    name: "ناريمان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 449,
    parent: 396,
    name: "نجيب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 450,
    parent: 396,
    name: "جمال",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 451,
    parent: 396,
    name: "عبد الغني",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 452,
    parent: 396,
    name: "عبد المطلب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 453,
    parent: 396,
    name: "عبد الحكيم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 454,
    parent: 396,
    name: "عبد المؤمن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 455,
    parent: 396,
    name: "سعاد",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 456,
    parent: 396,
    name: "شفيقة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 457,
    parent: 396,
    name: "السيدة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 458,
    parent: 396,
    name: "هندة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 459,
    parent: 396,
    name: "وداد",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 460,
    parent: 396,
    name: "عفيفة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 461,
    parent: 451,
    name: "أمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 462,
    parent: 451,
    name: "آمنة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 463,
    parent: 451,
    name: "زينب",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 464,
    parent: 449,
    name: "طلال",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 465,
    parent: 449,
    name: "إلياس",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 466,
    parent: 449,
    name: "منى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 467,
    parent: 449,
    name: "انتصار",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 468,
    parent: 450,
    name: "طارق",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 469,
    parent: 450,
    name: "زكرياء",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 470,
    parent: 450,
    name: "ألفة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 471,
    parent: 450,
    name: "شروق",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 472,
    parent: 453,
    name: "زياد",
    gender: Gender.M,
    birthYear: "1991",
  },
  {
    key: 473,
    parent: 453,
    name: "أسماء",
    gender: Gender.F,
    birthYear: "1998",
  },
  {
    key: 474,
    parent: 472,
    name: "مالك",
    gender: Gender.M,
    birthYear: "2021",
  },
  {
    key: 475,
    parent: 452,
    name: "حمزة",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 476,
    parent: 452,
    name: "عبير",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 477,
    parent: 452,
    name: "خلود",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 478,
    parent: 452,
    name: "ضحى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 479,
    parent: 454,
    name: "إبراهيم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 480,
    parent: 454,
    name: "زينب",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 481,
    parent: 454,
    name: "آمنة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 482,
    parent: 454,
    name: "إيمان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 483,
    parent: 395,
    name: "صلاح الدين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 484,
    parent: 395,
    name: "فيصل",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 485,
    parent: 395,
    name: "مثنى",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 486,
    parent: 395,
    name: "طارق",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 487,
    parent: 395,
    name: "نجاة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 488,
    parent: 395,
    name: "منيرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 489,
    parent: 395,
    name: "ليلى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 490,
    parent: 395,
    name: "شهرزاد",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 491,
    parent: 483,
    name: "علاء",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 492,
    parent: 483,
    name: "أيمن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 493,
    parent: 483,
    name: "ندين",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 494,
    parent: 483,
    name: "فرح",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 495,
    parent: 484,
    name: "سامي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 496,
    parent: 484,
    name: "مهدي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 497,
    parent: 485,
    name: "أحمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 498,
    parent: 485,
    name: "ناريمان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 499,
    parent: 486,
    name: "ريم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 500,
    parent: 486,
    name: "رؤى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 501,
    parent: 486,
    name: "ليال",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 502,
    parent: 486,
    name: "لينا",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 503,
    parent: 2,
    name: "بنعزوز",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 504,
    parent: 2,
    name: "العربي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 505,
    parent: 2,
    name: "عبد الحفيظ",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 506,
    parent: 2,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 507,
    parent: 2,
    name: "سعد السعود",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 508,
    parent: 503,
    name: "الحنافي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 509,
    parent: 503,
    name: "مصطفى",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 510,
    parent: 503,
    name: "الفضل",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 511,
    parent: 503,
    name: "توفيق",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 512,
    parent: 503,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 513,
    parent: 503,
    name: "مليكة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 514,
    parent: 503,
    name: "بية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 515,
    parent: 504,
    name: "جمال",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 516,
    parent: 504,
    name: "نجم السعود",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 517,
    parent: 504,
    name: "حسن",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 518,
    parent: 504,
    name: "محمد النوري",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 519,
    parent: 518,
    name: "عبد الرحمان",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 520,
    parent: 518,
    name: "رشيد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 521,
    parent: 518,
    name: "فيصل",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 522,
    parent: 518,
    name: "رجاء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 523,
    parent: 518,
    name: "زينة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 524,
    parent: 518,
    name: "ابتسام",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 525,
    parent: 518,
    name: "هناء",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 526,
    parent: 518,
    name: "فيروز",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 527,
    parent: 518,
    name: "نادية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 528,
    parent: 518,
    name: "نسيمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 529,
    parent: 518,
    name: "أمل",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 530,
    parent: 521,
    name: "عبد الرؤوف",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 531,
    parent: 530,
    name: "مروان",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 532,
    parent: 530,
    name: "إيمان",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 533,
    parent: 505,
    name: "محمد الأمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 534,
    parent: 505,
    name: "عبد المجيد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 535,
    parent: 505,
    name: "عبد الحميد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 536,
    parent: 505,
    name: "محمد الأزهري",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 537,
    parent: 505,
    name: "محمود",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 538,
    parent: 505,
    name: "المكي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 539,
    parent: 505,
    name: "المداني",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 540,
    parent: 505,
    name: "التارزي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 541,
    parent: 534,
    name: "الأمين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 542,
    parent: 534,
    name: "شهرة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 543,
    parent: 534,
    name: "كوكب الصباح",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 544,
    parent: 535,
    name: "عبد العزيز",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 545,
    parent: 535,
    name: "عبد العال",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 546,
    parent: 535,
    name: "قمر الزمان",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 547,
    parent: 535,
    name: "جميلة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 548,
    parent: 535,
    name: "قوت القلوب",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 549,
    parent: 536,
    name: "محمد الطيب",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 550,
    parent: 536,
    name: "محمد الصالح",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 551,
    parent: 536,
    name: "محمد فوزي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 552,
    parent: 536,
    name: "حسني",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 553,
    parent: 536,
    name: "نفيسة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 554,
    parent: 536,
    name: "شافية",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 555,
    parent: 550,
    name: "محمد الأزهاري",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 556,
    parent: 550,
    name: "حسين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 557,
    parent: 550,
    name: "رضا",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 558,
    parent: 550,
    name: "إلياس",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 559,
    parent: 550,
    name: "حمزة",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 560,
    parent: 555,
    name: "محمد الصالح إياد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 561,
    parent: 555,
    name: "أيهم",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 562,
    parent: 555,
    name: "ميرنا ميرال",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 563,
    parent: 556,
    name: "أحمد جود",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 564,
    parent: 556,
    name: "محمد",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 565,
    parent: 556,
    name: "أنس",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 566,
    parent: 557,
    name: "مريم",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 567,
    parent: 557,
    name: "ليتيسيا",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 568,
    parent: 557,
    name: "أنيا رحمة",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 569,
    parent: 558,
    name: "هديل",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 570,
    parent: 558,
    name: "أسيل",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 571,
    parent: 558,
    name: "ثريا",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 572,
    parent: 3,
    name: "شمس الدين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 573,
    parent: 3,
    name: "زين الدين",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 574,
    parent: 3,
    name: "حياة النفوس",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 575,
    parent: 3,
    name: "نور الهدى",
    gender: Gender.F,
    birthYear: "-",
  },
  {
    key: 576,
    parent: 507,
    name: "جيلاني",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 577,
    parent: 507,
    name: "محمد الهادي",
    gender: Gender.M,
    birthYear: "-",
  },
  {
    key: 578,
    parent: 507,
    name: "شهيد",
    gender: Gender.M,
    birthYear: "-",
  },
];

export default nodeDataArray;
